[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
        "@chainlink/contracts/=lib/chainlink/contracts/",
    "foundry-devops/=lib/foundry-devops/src/",
    "forge-std/=lib/forge-std/src/"

]
fs_permissions = [{ access = "read", path = "./" }]
