[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
      "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "foundry-devops/=lib/foundry-devops/",
    "forge-std/=lib/forge-std/src/"
]
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./" }]