[default]
src = "src"
out = "out"
libs = ["lib"]

[profile.default]
optimizer = true
optimizer_runs = 200

[profile.remappings]
"foundry-devops/" = "lib/foundry-devops/src/"
"forge-std/" = "lib/forge-std/src/"
"@chainlink/contracts/" = "lib/chainlink-brownie-contracts/contracts/"
"chainlink/" = "lib/chainlink/"
